# Broker服务独立配置
name: bento-broker

# 基础环境变量定义
x-base-environment: &base-environment
  # Using pgbouncer for connection pooling
  DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@pgbouncer:5432/${POSTGRES_DB:-taskdb}
  REDIS_URL: redis://redis:6379
  S3_URL: http://minio:9000
  S3_BUCKET: ${MINIO_BUCKET:-workflow}
  S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
  S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
  RUST_LOG: ${RUST_LOG:-info}
  RISC0_HOME: /usr/local/risc0
  RUST_BACKTRACE: 1

  # PoVW Configuration (official standard - minimal approach)
  POVW_LOG_ID: ${POVW_LOG_ID:-}
  RPC_URL: ${RPC_URL:-}
  PRIVATE_KEY: ${PRIVATE_KEY:-}
  # 内网代理排除配置
  no_proxy: localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer
  NO_PROXY: localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer

services:
  # Broker service
  broker:
    restart: always
    build:
      context: .
      dockerfile: ${BROKER_DOCKERFILE:-dockerfiles/broker.prebuilt.dockerfile}
      args:
        BINARY_URL: ${BROKER_BINARY_URL:-https://github.com/boundless-xyz/boundless/releases/download/broker-v1.0.0/broker}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        no_proxy: ${no_proxy:-localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer}
        NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer}
    mem_limit: 2G
    cpus: 2
    stop_grace_period: 3h
    volumes:
      - type: bind
        source: ./broker.toml
        target: /app/broker.toml
      - broker-data:/db/
    environment:
      RUST_LOG: ${RUST_LOG:-info,broker=debug,boundless_market=debug}
      PRIVATE_KEY: ${PRIVATE_KEY}
      RPC_URL: http://5.39.222.250:9301
      BOUNDLESS_MARKET_ADDRESS:
      SET_VERIFIER_ADDRESS:
      ORDER_STREAM_URL:
      POSTGRES_HOST:
      POSTGRES_DB:
      POSTGRES_PORT:
      POSTGRES_USER:
      POSTGRES_PASS:
      no_proxy: localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer
      NO_PROXY: localhost,127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,minio,postgres,redis,pgbouncer

    entrypoint: /app/broker --db-url 'sqlite:///db/broker.db' --config-file /app/broker.toml --bento-api-url http://host.docker.internal:8081
    networks:
       - bento-network

networks:
  bento-network:
    external: true
    name: bento-master_bento-network

volumes:
  broker-data: