# Worker节点配置 - 优化版：只运行GPU和Exec agents
name: bento-worker

# 基础环境变量定义 - 通过Master的pgbouncer连接池
x-base-environment: &base-environment
  DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${MASTER_HOST_IP:-172.31.0.9}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
  REDIS_URL: redis://${MASTER_HOST_IP:-172.31.0.9}:6379
  S3_URL: http://${MASTER_HOST_IP:-172.31.0.9}:9000
  S3_BUCKET: ${MINIO_BUCKET:-workflow}
  S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
  S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
  RUST_LOG: ${RUST_LOG:-info}
  RUST_BACKTRACE: 1
  # 内网优化配置
  no_proxy: "localhost,127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
  NO_PROXY: "localhost,127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"

services:
  # GPU Prove Agents (Worker节点8个GPU)
  gpu_prove_agent0: &gpu-agent
    image: risczero/risc0-bento-agent:2.3.0@sha256:5b029fb8074b3273b45e6e8fb4d6dbd86000a216688d8f1429eb893686cc1ff8
    runtime: nvidia
    restart: always
    mem_limit: 24G
    cpus: 4
    environment:
      <<: *base-environment
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - worker-network

  gpu_prove_agent1: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  gpu_prove_agent2: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]

  gpu_prove_agent3: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]

  gpu_prove_agent4: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['4']
              capabilities: [gpu]

  gpu_prove_agent5: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['5']
              capabilities: [gpu]

  gpu_prove_agent6: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['6']
              capabilities: [gpu]

  gpu_prove_agent7: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['7']
              capabilities: [gpu]

  # Executor Agents (Worker节点2个Exec agents)
  # exec_agent0: &exec-agent
  #   image: risczero/risc0-bento-agent:2.3.0@sha256:5b029fb8074b3273b45e6e8fb4d6dbd86000a216688d8f1429eb893686cc1ff8
  #   restart: always
  #   mem_limit: 4G
  #   cpus: 4
  #   environment:
  #     <<: *base-environment
  #   entrypoint: /app/agent -t exec --segment-po2 ${SEGMENT_SIZE:-21} --redis-ttl ${REDIS_TTL:-57600}
  #   networks:
  #     - worker-network

  # exec_agent1: 
  #   <<: *exec-agent

networks:
  worker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

# Worker节点使用集中式服务，无需本地存储卷