# Worker节点配置 - 优化版：只运行GPU和Exec agents
name: bento-worker

# 基础环境变量定义 - 通过Master的pgbouncer连接池
x-base-environment: &base-environment
  DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${MASTER_HOST_IP:-172.31.0.9}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
  REDIS_URL: redis://${MASTER_HOST_IP:-172.31.0.9}:6379
  S3_URL: http://${MASTER_HOST_IP:-172.31.0.9}:9000
  S3_BUCKET: ${MINIO_BUCKET:-workflow}
  S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
  S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
  RUST_LOG: ${RUST_LOG:-info}
  RUST_BACKTRACE: 1
  # 内网优化配置
  no_proxy: "localhost,127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
  NO_PROXY: "localhost,127.0.0.1,::1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"

# Agent 通用配置
x-agent-common: &agent-common
  runtime: nvidia
  build:
    context: .
    dockerfile: ${AGENT_DOCKERFILE:-dockerfiles/agent.prebuilt.dockerfile}
    args:
      BINARY_URL: ${BENTO_BINARY_URL:-https://github.com/boundless-xyz/boundless/releases/download/bento-v0.14.0/bento-bundle-linux-amd64.tar.gz}
  restart: always
  environment:
    <<: *base-environment

# 统一agent镜像版本管理
x-agent-image: &agent-image risczero/risc0-bento-agent:2.3.0

services:
  # GPU Prove Agents (Worker节点8个GPU)
  gpu_prove_agent0: &gpu-agent
    <<: *agent-common
    mem_limit: 64G
    cpus: 16
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent1: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent2: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent3: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent4: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['4']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent5: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['5']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent6: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['6']
              capabilities: [gpu]
    network_mode: host

  gpu_prove_agent7: 
    <<: *gpu-agent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['7']
              capabilities: [gpu]
    network_mode: host

  # Executor Agents (Worker节点2个Exec agents)
  # exec_agent0: &exec-agent
  #   image: risczero/risc0-bento-agent:2.3.0@sha256:5b029fb8074b3273b45e6e8fb4d6dbd86000a216688d8f1429eb893686cc1ff8
  #   restart: always
  #   mem_limit: 4G
  #   cpus: 4
  #   environment:
  #     <<: *base-environment
  #   entrypoint: /app/agent -t exec --segment-po2 ${SEGMENT_SIZE:-21} --redis-ttl ${REDIS_TTL:-57600}
  #   networks:
  #     - worker-network

  # exec_agent1: 
  #   <<: *exec-agent

# 使用host网络模式，无需自定义网络配置

# Worker节点使用集中式服务，无需本地存储卷